# CSI5388 Natural Language Processing
## Assignment - 2
## INGREDIENTS FOR HAPPINESS

In [1]:
# Import Data
import pandas as pd
import numpy as np
train_labeled = pd.read_csv("data/TRAIN/labeled_10k.csv", engine = 'python')
train_unlabeled = pd.read_csv("data/TRAIN/unlabeled_70k.csv", engine = 'python')
test_labeled = pd.read_csv("data/TEST/labeled_17k.csv", engine = 'python',encoding='cp1252') # engine should be set as python to avoid error due to some characters: https://stackoverflow.com/questions/46000191/utf-8-codec-cant-decode-byte-0x92-in-position-18-invalid-start-byte
test_unlabeled = pd.read_csv("data/TEST/unlabeled_17k.csv", engine = 'python',encoding='cp1252')

In [2]:
train_labeled.head()

hmid                                             moment          concepts  \
0  27674  I was happy when my son got 90% marks in his e...  education|family   
1  27685          went to movies with my friends it was fun     entertainment   
2  27691  A hot kiss with my girl friend last night made...           romance   
3  27701  My son woke me up to a fantastic breakfast of ...       family|food   
4  27712  My older daughter keeps patting my younger dau...            family   

  agency social   age country gender  married parenthood reflection  \
0     no    yes  29.0     IND      m  married          y        24h   
1    yes    yes  29.0     IND      m   single          y        24h   
2    yes    yes  25.0     IND      m  married          y        24h   
3     no    yes    79     USA      f  widowed          y        24h   
4     no    yes    30     USA      f  married          y        24h   

                      duration  
0                   half_a_day  
1                   half_a_day  
2            at_least_one_hour  
3  all_day_im_still_feeling_it  
4                 a_few_moment

In [3]:
train_unlabeled.head()

hmid                                             moment   age country  \
0  27673  I went on a successful date with someone I fel...  35.0     USA   
1  27675       I went to the gym this morning and did yoga.  30.0     USA   
2  27678                            I meditated last night.  23.0     IND   
3  27679  I made a new recipe for peasant bread, and it ...  30.0     USA   
4  27680  I got gift from my elder brother which was rea...  23.0     IND   

  gender  married parenthood reflection           duration  
0      m   single          n        24h  at_least_one_hour  
1      f  married          y        24h  at_least_one_hour  
2      m   single          n        24h  at_least_one_hour  
3      m   single          n        24h         half_a_day  
4      m   single          n        24h  at_least_one_hour

In [4]:
test_labeled.head()

hmid                                             moment reflection age  \
0     0  I was able to spend the day with my fiance sho...        24h  28   
1     1                    I was able to play with my cat.        24h  28   
2     2   I was able to clean my room and gold my laundry.        24h  28   
3     3  I spend the day at a party on the beach and I ...        24h  24   
4     4  My cat greeting me when I got home from work -...        24h  24   

  country gender                     duration married parenthood  \
0     USA      m  all_day_im_still_feeling_it  single          n   
1     USA      m            at_least_one_hour  single          n   
2     USA      m            at_least_one_hour  single          n   
3     USA      m                   half_a_day  single          n   
4     USA      m                   half_a_day  single          n   

                  concepts agency social  
0  shopping|family|romance    yes     no  
1                  animals    yes     no  
2                        0    yes     no  
3   vacation|party|weather    yes    yes  
4                  animals     no     no

In [5]:
test_unlabeled.head()

hmid                                             moment reflection age  \
0     0  I was able to spend the day with my fiance sho...        24h  28   
1     1                    I was able to play with my cat.        24h  28   
2     2   I was able to clean my room and gold my laundry.        24h  28   
3     3  I spend the day at a party on the beach and I ...        24h  24   
4     4  My cat greeting me when I got home from work -...        24h  24   

  country gender                     duration married parenthood  
0     USA      m  all_day_im_still_feeling_it  single          n  
1     USA      m            at_least_one_hour  single          n  
2     USA      m            at_least_one_hour  single          n  
3     USA      m                   half_a_day  single          n  
4     USA      m                   half_a_day  single          n

### Pre-processing ###

In [6]:
import nltk

In [7]:
train_labeled['moment'].head(3)

0    I was happy when my son got 90% marks in his e...
1            went to movies with my friends it was fun
2    A hot kiss with my girl friend last night made...
Name: moment, dtype: object

In [8]:
train_unlabeled['moment'].head(3)

0    I went on a successful date with someone I fel...
1         I went to the gym this morning and did yoga.
2                              I meditated last night.
Name: moment, dtype: object

In [9]:
train_labeled['moment'] = train_labeled['moment'].str.lower()
train_unlabeled['moment'] = train_unlabeled['moment'].str.lower()

In [10]:
train_unlabeled['moment'].head(3)

0    i went on a successful date with someone i fel...
1         i went to the gym this morning and did yoga.
2                              i meditated last night.
Name: moment, dtype: object

## Removing the punctuations ##

In [11]:
import string
print(string.punctuation)
punct_str = string.punctuation

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [12]:
upd_moment = []
upd_moment_2 = []

for text_t1 in train_labeled['moment']:
    text_upd = "".join([ char for char in text_t1 if char not in string.punctuation])
    upd_moment.append(text_upd)
    
for text_t2 in train_unlabeled['moment']:
    text_upd_2 = "".join([ char for char in text_t2 if char not in string.punctuation])
    upd_moment_2.append(text_upd_2)

In [13]:
train_labeled['moment'] = upd_moment
train_unlabeled['moment']= upd_moment_2

In [14]:
train_labeled['moment'][4]

'my older daughter keeps patting my younger daughters head'

## Tokenization ##

In [15]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('corpus')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\parit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\parit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index


False

In [16]:
from nltk import word_tokenize
list_tokenize = []

for moments_sent in train_labeled['moment']:
    tokenized_wrds = word_tokenize(moments_sent)
    list_tokenize.append(tokenized_wrds)
train_labeled['moment'] = list_tokenize
    
list_tokenize = []
for moments_sent in train_unlabeled['moment']:
    tokenized_wrds = word_tokenize(moments_sent)
    list_tokenize.append(tokenized_wrds)
train_unlabeled['moment'] = list_tokenize


In [17]:
train_labeled.head()

hmid                                             moment          concepts  \
0  27674  [i, was, happy, when, my, son, got, 90, marks,...  education|family   
1  27685  [went, to, movies, with, my, friends, it, was,...     entertainment   
2  27691  [a, hot, kiss, with, my, girl, friend, last, n...           romance   
3  27701  [my, son, woke, me, up, to, a, fantastic, brea...       family|food   
4  27712  [my, older, daughter, keeps, patting, my, youn...            family   

  agency social   age country gender  married parenthood reflection  \
0     no    yes  29.0     IND      m  married          y        24h   
1    yes    yes  29.0     IND      m   single          y        24h   
2    yes    yes  25.0     IND      m  married          y        24h   
3     no    yes    79     USA      f  widowed          y        24h   
4     no    yes    30     USA      f  married          y        24h   

                      duration  
0                   half_a_day  
1                   half_a_day  
2            at_least_one_hour  
3  all_day_im_still_feeling_it  
4                 a_few_moment

In [18]:
train_unlabeled.head()

hmid                                             moment   age country  \
0  27673  [i, went, on, a, successful, date, with, someo...  35.0     USA   
1  27675  [i, went, to, the, gym, this, morning, and, di...  30.0     USA   
2  27678                        [i, meditated, last, night]  23.0     IND   
3  27679  [i, made, a, new, recipe, for, peasant, bread,...  30.0     USA   
4  27680  [i, got, gift, from, my, elder, brother, which...  23.0     IND   

  gender  married parenthood reflection           duration  
0      m   single          n        24h  at_least_one_hour  
1      f  married          y        24h  at_least_one_hour  
2      m   single          n        24h  at_least_one_hour  
3      m   single          n        24h         half_a_day  
4      m   single          n        24h  at_least_one_hour

## Remove Stopwords  ##

In [19]:
from nltk.corpus import stopwords
stop_words_eng = stopwords.words('english')
print(stop_words_eng)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [20]:
filt_wrd_list=[]
for words in train_labeled['moment']:
    filtered_words = [word for word in words if word not in stop_words_eng]    
    filt_wrd_list.append(filtered_words)
train_labeled['moment'] = filt_wrd_list

filt_wrd_list=[]
for words in train_unlabeled['moment']:
    filtered_words = [word for word in words if word not in stop_words_eng]    
    filt_wrd_list.append(filtered_words)
train_unlabeled['moment'] = filt_wrd_list

In [21]:
train_labeled['moment']

0                [happy, son, got, 90, marks, examination]
1                             [went, movies, friends, fun]
2        [hot, kiss, girl, friend, last, night, made, day]
3        [son, woke, fantastic, breakfast, eggs, specia...
4        [older, daughter, keeps, patting, younger, dau...
                               ...                        
10555                       [husband, called, tell, loved]
10556                  [worked, always, makes, feel, good]
10557    [finally, got, watch, new, resident, evil, movie]
10558     [got, talk, old, friend, reminisce, good, times]
10559    [great, meeting, yesterday, work, boss, collea...
Name: moment, Length: 10560, dtype: object

In [22]:
train_unlabeled['moment']

0        [went, successful, date, someone, felt, sympat...
1                               [went, gym, morning, yoga]
2                                 [meditated, last, night]
3        [made, new, recipe, peasant, bread, came, spec...
4          [got, gift, elder, brother, really, surprising]
                               ...                        
72319                              [spent, time, daughter]
72320    [husband, announced, getting, decent, bonus, q...
72321                                       [pepsi, drink]
72322                  [cuddling, girlfriend, last, night]
72323                        [great, workout, last, night]
Name: moment, Length: 72324, dtype: object

## Lemmatizer ##

In [23]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\parit\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [24]:
# lemm_wrd_list=[]
# for words in train_labeled['moment']:
#     lemm_words = [lemmatizer.lemmatize(word) for word in words]    
#     lemm_wrd_list.append(lemm_words)

# train_labeled['moment'] = lemm_wrd_list
lemm_wrd_list=[]
for words in train_labeled['moment']:
    lemm_words = [lemmatizer.lemmatize(word) for word in words] 
    lemm_string = "";
    for i in range(0, len(lemm_words)):
        lemm_string += lemm_words[i] + " "
    lemm_wrd_list.append(lemm_string.strip())
train_labeled['moment'] = lemm_wrd_list

In [25]:
train_labeled.head()

hmid                                             moment          concepts  \
0  27674                  happy son got 90 mark examination  education|family   
1  27685                              went movie friend fun     entertainment   
2  27691           hot kiss girl friend last night made day           romance   
3  27701  son woke fantastic breakfast egg special hambu...       family|food   
4  27712  older daughter keep patting younger daughter head            family   

  agency social   age country gender  married parenthood reflection  \
0     no    yes  29.0     IND      m  married          y        24h   
1    yes    yes  29.0     IND      m   single          y        24h   
2    yes    yes  25.0     IND      m  married          y        24h   
3     no    yes    79     USA      f  widowed          y        24h   
4     no    yes    30     USA      f  married          y        24h   

                      duration  
0                   half_a_day  
1                   half_a_day  
2            at_least_one_hour  
3  all_day_im_still_feeling_it  
4                 a_few_moment

In [26]:
# lemm_wrd_list=[]
# for words in train_unlabeled['moment']:
#     lemm_words = [lemmatizer.lemmatize(word) for word in words]    
#     lemm_wrd_list.append(lemm_words)

lemm_wrd_list=[]
for words in train_unlabeled['moment']:
    lemm_words = [lemmatizer.lemmatize(word) for word in words] 
    lemm_string = "";
    for i in range(0, len(lemm_words)):
        lemm_string += lemm_words[i] + " "
    lemm_wrd_list.append(lemm_string.strip())

train_unlabeled['moment'] = lemm_wrd_list

In [27]:
concepts_list = []
for i in range(0, len(train_labeled['concepts'])):
    arr = train_labeled['concepts'][i].split("|")
    concept_string = ""
    for j in range(0, len(arr)):
        concept_string += arr[j] + " "
    concepts_list.append(concept_string.strip())
train_labeled['concepts'] = concepts_list

In [28]:
train_labeled.head()

hmid                                             moment          concepts  \
0  27674                  happy son got 90 mark examination  education family   
1  27685                              went movie friend fun     entertainment   
2  27691           hot kiss girl friend last night made day           romance   
3  27701  son woke fantastic breakfast egg special hambu...       family food   
4  27712  older daughter keep patting younger daughter head            family   

  agency social   age country gender  married parenthood reflection  \
0     no    yes  29.0     IND      m  married          y        24h   
1    yes    yes  29.0     IND      m   single          y        24h   
2    yes    yes  25.0     IND      m  married          y        24h   
3     no    yes    79     USA      f  widowed          y        24h   
4     no    yes    30     USA      f  married          y        24h   

                      duration  
0                   half_a_day  
1                   half_a_day  
2            at_least_one_hour  
3  all_day_im_still_feeling_it  
4                 a_few_moment

## Preprocessing Other Columns ##

In [29]:
train_labeled['country'].unique()

array(['IND', 'USA', 'VEN', 'DNK', 'FIN', 'PER', 'GBR', 'SRB', 'DOM',
       'ARM', 'PAK', 'SGP', 'FRA', 'JAM', 'LTU', 'TUR', 'PHL', 'PRT',
       'ESP', 'THA', 'MEX', 'ARE', 'IDN', 'BRA', 'IRL', 'NGA', 'CAN',
       'BGR', 'DEU', nan, 'DZA', 'MKD', 'ETH', 'RUS', 'EGY', 'NLD', 'ALB',
       'BEL', 'MDA', 'ISR', 'NZL', 'AUS', 'ZAF', 'SWE', 'VNM', 'KAZ',
       'GRC', 'TTO', 'UGA', 'MAR', 'URY', 'ISL', 'SUR', 'KOR', 'BHS',
       'COL', 'ITA', 'CZE', 'BRB', 'MLT', 'MYS', 'KEN', 'KWT', 'PRI',
       'ROU', 'SVN', 'MAC', 'GTM', 'NOR', 'AFG'], dtype=object)

In [30]:
train_unlabeled['country'].unique()

array(['USA', 'IND', 'VNM', 'KWT', 'GBR', 'FIN', 'AUS', 'BGD', 'IDN',
       'BEL', 'CAN', 'SGP', 'IRL', 'PHL', 'VEN', 'LTU', 'BGR', 'DNK',
       'URY', 'SRB', 'JAM', 'ITA', 'KEN', 'DOM', 'EGY', 'PER', 'PRT',
       'ESP', 'NGA', 'BRA', 'MEX', 'TUR', 'MKD', 'FRA', 'COL', 'GRC', nan,
       'MDA', 'POL', 'ARM', 'PAK', 'DZA', 'UGA', 'MYS', 'ZAF', 'THA',
       'ARE', 'AUT', 'LKA', 'DEU', 'ROU', 'ETH', 'NZL', 'NIC', 'NLD',
       'ALB', 'RUS', 'UMI', 'ISR', 'MAR', 'SWE', 'KAZ', 'ASM', 'TTO',
       'JPN', 'PRI', 'AFG', 'KNA', 'CYP', 'TUN', 'HRV', 'ECU', 'KOR',
       'BRB', 'CZE', 'EST', 'BHS', 'GTM', 'GHA', 'GMB', 'ISL', 'SAU',
       'SUR', 'MLT', 'TCA', 'IRQ', 'ARG', 'TWN', 'CHL', 'MAC', 'SVN',
       'NPL', 'VIR', 'SLV', 'NOR', 'LVA'], dtype=object)

- First issue the unlabelled data set has more terms different from the labelled data 
- Agency and Social are TARGET

In [31]:
train_labeled.columns

Index(['hmid', 'moment', 'concepts', 'agency', 'social', 'age', 'country',
       'gender', 'married', 'parenthood', 'reflection', 'duration'],
      dtype='object')

In [32]:
# print(train_labeled['married'].unique())
# print(train_labeled['gender'].unique())
# print(train_labeled['age'].unique())
# print(train_labeled['duration'].unique())
# print(train_labeled['reflection'].unique())
# print(train_labeled['parenthood'].unique())
# print(train_labeled['concepts'].unique())

In [33]:
print(train_labeled.isna().sum())

hmid           0
moment         0
concepts       0
agency         0
social         0
age            9
country       22
gender         6
married       15
parenthood     9
reflection     0
duration      31
dtype: int64


In [34]:
print(train_unlabeled.isna().sum())

hmid            0
moment          0
age            96
country       124
gender         47
married        95
parenthood     50
reflection      0
duration      226
dtype: int64


In [35]:
print(test_labeled.isna().sum())

hmid            0
moment          0
reflection      0
age             0
country       262
gender         50
duration        0
married       215
parenthood    122
concepts        0
agency          0
social          0
dtype: int64


In [36]:
print(test_unlabeled.isna().sum())

hmid            0
moment          0
reflection      0
age             0
country       262
gender         50
duration        0
married       215
parenthood    122
dtype: int64


## Remove all the nan, null and prefer not to say values ##

In [37]:
train_labeled.shape

(10560, 12)

In [38]:
train_labeled = train_labeled.dropna()
print(train_labeled.shape)

(10485, 12)


In [39]:
train_unlabeled.shape

(72324, 9)

In [40]:
train_unlabeled = train_unlabeled.dropna()
train_unlabeled.shape

(71771, 9)

In [41]:
test_labeled = test_labeled.dropna()
test_labeled.shape

(16665, 12)

In [42]:
test_unlabeled = test_unlabeled.dropna()
test_unlabeled.shape

(16665, 9)

In [43]:
# print(train_labeled['married'].unique())
# print(train_labeled['gender'].unique())
# print(train_labeled['duration'].unique())
# print(train_labeled['reflection'].unique())
# print(train_labeled['parenthood'].unique())
# print(train_labeled['age'].unique())
# print(train_labeled['country'].unique())
# print(train_labeled['country'].describe())

In [44]:
#print(train_labeled.shape)
train_labeled = train_labeled[train_labeled["age"].str.contains("prefer not to say") == False]
#print(train_labeled.shape)

train_labeled['age'] = train_labeled['age'].astype(float)

In [45]:
# print(test_labeled['married'].unique())
# print(test_labeled['gender'].unique())
print(test_labeled['duration'].unique())

cnt=0
for i in test_labeled['duration']:
    if i=='select one':
        cnt+=1;
print('\nRows with "Select One" word ',cnt,'\n')



# print(test_labeled['reflection'].unique())
# print(test_labeled['parenthood'].unique())
print(test_labeled['age'].unique())
# print(test_labeled['country'].unique())
print(test_labeled['country'].describe())

['all_day_im_still_feeling_it' 'at_least_one_hour' 'half_a_day'
 'a_few_minutes' 'select one']

Rows with "Select One" word  45 

['28' '24' '34' '27' '31' '21' '57' '36' '71' '32' '40' '43' '38' '30'
 '49' '25' '46' '35' '69' '26' '29' '19' '33' '54' '23' '45' '72' '41'
 '22' '56' '70' '60' '37' '51' '50' '48' '39' '55' '47' '62' '74' '61'
 '68' '65' '59' '20' '67' '{}' '42' '44' '66' '64' '18' '76' '58' '63'
 '52' '53' '78' '73' '2' '3' '119' '5' '37years' '80' ',30' '247' '586']
count     16665
unique       61
top         USA
freq      13952
Name: country, dtype: object


In [46]:
print(train_unlabeled['married'].unique())
print(train_unlabeled['gender'].unique())
print(train_unlabeled['duration'].unique())
print(train_unlabeled['reflection'].unique())
print(train_unlabeled['parenthood'].unique())
print(train_unlabeled['age'].unique())

['single' 'married' 'divorced' 'separated' 'widowed']
['m' 'f' 'o']
['at_least_one_hour' 'half_a_day' 'all_day_im_still_feeling_it'
 'a_few_moment' 'a_few_minutes']
['24h' '3m']
['n' 'y']
[ 35.  30.  23.  25.  41.  37.  29.  39.  28.  38.  27.  22.  47.  26.
  64.  32.  33.  48.  61.  66.  36.  18.  56.  31.  42.  24.  62.  44.
  21.  45.  46.  40.  55.   3.  52.  19.  34.  53.  49.  65.  43.  20.
  51.  50.  54.  69.  57.  63.  60.  73.  58.  71.  98.  70.  59. 227.
  68.  72.  83.   2.  78.  76.  67.  74.  81. 233.  79.  95.  80.  88.
  75.  77.]


In [47]:
print(test_unlabeled['married'].unique())
print(test_unlabeled['gender'].unique())
print(test_unlabeled['duration'].unique())
print(test_unlabeled['reflection'].unique())
print(test_unlabeled['parenthood'].unique())
print(test_unlabeled['age'].unique())

['single' 'married' 'divorced' 'separated' 'widowed']
['m' 'f' 'o']
['all_day_im_still_feeling_it' 'at_least_one_hour' 'half_a_day'
 'a_few_minutes' 'select one']
['24h' '3m']
['n' 'y']
['28' '24' '34' '27' '31' '21' '57' '36' '71' '32' '40' '43' '38' '30'
 '49' '25' '46' '35' '69' '26' '29' '19' '33' '54' '23' '45' '72' '41'
 '22' '56' '70' '60' '37' '51' '50' '48' '39' '55' '47' '62' '74' '61'
 '68' '65' '59' '20' '67' '{}' '42' '44' '66' '64' '18' '76' '58' '63'
 '52' '53' '78' '73' '2' '3' '119' '5' '37years' '80' ',30' '247' '586']


In [48]:
print(test_labeled['married'].unique())
print(test_labeled['gender'].unique())
print(test_labeled['duration'].unique())
print(test_labeled['reflection'].unique())
print(test_labeled['parenthood'].unique())

['single' 'married' 'divorced' 'separated' 'widowed']
['m' 'f' 'o']
['all_day_im_still_feeling_it' 'at_least_one_hour' 'half_a_day'
 'a_few_minutes' 'select one']
['24h' '3m']
['n' 'y']


In [49]:
print(train_labeled['agency'].unique())
print(train_labeled['social'].unique())

['no' 'yes']
['yes' 'no']


In [50]:
train_unlabeled.columns

Index(['hmid', 'moment', 'age', 'country', 'gender', 'married', 'parenthood',
       'reflection', 'duration'],
      dtype='object')

In [51]:
train_labeled.columns

Index(['hmid', 'moment', 'concepts', 'agency', 'social', 'age', 'country',
       'gender', 'married', 'parenthood', 'reflection', 'duration'],
      dtype='object')

In [52]:
test_labeled.columns

Index(['hmid', 'moment', 'reflection', 'age', 'country', 'gender', 'duration',
       'married', 'parenthood', 'concepts', 'agency', 'social'],
      dtype='object')

In [53]:
test_unlabeled.columns

Index(['hmid', 'moment', 'reflection', 'age', 'country', 'gender', 'duration',
       'married', 'parenthood'],
      dtype='object')

## Encoding the columns ##

In [54]:
# Dealing with yes->1 and No->0 # for agency and social#
train_labeled['social'].replace({'yes':1,'no':0},inplace=True)
train_labeled['agency'].replace({'yes':1,'no':0},inplace=True)

In [55]:
# Dealing with yes->1 and No->0 # for agency and social#
test_labeled['social'].replace({'yes':1,'no':0},inplace=True)
test_labeled['agency'].replace({'yes':1,'no':0},inplace=True)

In [56]:
list1 = []
for i in train_labeled['country']:
    if i=='USA':
        list1.append(1)
    else:
        list1.append(0)

train_labeled['country'] = list1

list1 = []
for i in train_unlabeled['country']:
    if i=='USA':
        list1.append(1)
    else:
        list1.append(0)

train_unlabeled['country'] = list1

In [57]:
list2 = []
for i in test_labeled['country']:
    if i=='USA':
        list2.append(1)
    else:
        list2.append(0)

test_labeled['country'] = list2

list2 = []
for i in test_unlabeled['country']:
    if i=='USA':
        list2.append(1)
    else:
        list2.append(0)

test_unlabeled['country'] = list2

In [58]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder

In [60]:
label_enc_age = LabelEncoder()
label_enc_gender = LabelEncoder()
label_enc_parenthood = LabelEncoder()
label_enc_reflection = LabelEncoder()
label_enc_country = LabelEncoder()
label_enc_married = LabelEncoder()
label_enc_duration = LabelEncoder()

label_enc_age_test = LabelEncoder()
label_enc_duration_test = LabelEncoder()

label_enc_age_test_unl = LabelEncoder()


In [61]:
#train_labeled['age'] = label_enc_age.fit_transform(train_labeled['age'])
train_labeled['gender'] = label_enc_gender.fit_transform(train_labeled['gender'])
train_labeled['parenthood'] = label_enc_parenthood.fit_transform(train_labeled['parenthood'])
train_labeled['reflection'] = label_enc_reflection.fit_transform(train_labeled['reflection'])
train_labeled['country'] = label_enc_country.fit_transform(train_labeled['country'])
train_labeled['duration'] = label_enc_duration.fit_transform(train_labeled['duration'])
train_labeled['married'] = label_enc_married.fit_transform(train_labeled['married'])

#train_unlabeled['age'] = label_enc_age_new.fit_transform(train_unlabeled['age'])
train_unlabeled['gender'] = label_enc_gender.fit_transform(train_unlabeled['gender'])
train_unlabeled['parenthood'] = label_enc_parenthood.fit_transform(train_unlabeled['parenthood'])
train_unlabeled['reflection'] = label_enc_reflection.fit_transform(train_unlabeled['reflection'])
train_unlabeled['country'] = label_enc_country.fit_transform(train_unlabeled['country'])
train_unlabeled['duration'] = label_enc_duration.fit_transform(train_unlabeled['duration'])
train_unlabeled['married'] = label_enc_married.fit_transform(train_unlabeled['married'])


#test_labeled['age'] = label_enc_age_test.fit_transform(test_labeled['age'])
test_labeled['duration'] = label_enc_duration_test.fit_transform(test_labeled['duration'])
test_labeled['gender'] = label_enc_gender.fit_transform(test_labeled['gender'])
test_labeled['parenthood'] = label_enc_parenthood.fit_transform(test_labeled['parenthood'])
test_labeled['reflection'] = label_enc_reflection.fit_transform(test_labeled['reflection'])
test_labeled['country'] = label_enc_country.fit_transform(test_labeled['country'])
test_labeled['married'] = label_enc_married.fit_transform(test_labeled['married'])


#test_labeled['age'] = label_enc_age_test.fit_transform(test_labeled['age'])
test_unlabeled['duration'] = label_enc_duration_test.fit_transform(test_unlabeled['duration'])
test_unlabeled['gender'] = label_enc_gender.fit_transform(test_unlabeled['gender'])
test_unlabeled['parenthood'] = label_enc_parenthood.fit_transform(test_unlabeled['parenthood'])
test_unlabeled['reflection'] = label_enc_reflection.fit_transform(test_unlabeled['reflection'])
test_unlabeled['country'] = label_enc_country.fit_transform(test_unlabeled['country'])
test_unlabeled['married'] = label_enc_married.fit_transform(test_unlabeled['married'])


In [62]:
train_labeled

hmid                                             moment  \
0       27674                  happy son got 90 mark examination   
1       27685                              went movie friend fun   
2       27691           hot kiss girl friend last night made day   
3       27701  son woke fantastic breakfast egg special hambu...   
4       27712  older daughter keep patting younger daughter head   
...       ...                                                ...   
10555  128748                          husband called tell loved   
10556  128753                       worked always make feel good   
10557  128754          finally got watch new resident evil movie   
10558  128757            got talk old friend reminisce good time   
10559  128765  great meeting yesterday work bos colleague wen...   

               concepts  agency  social   age  country  gender  married  \
0      education family       0       1  29.0        0       1        1   
1         entertainment       1       1  29.0        0       1        3   
2               romance       1       1  25.0        0       1        1   
3           family food       0       1  79.0        1       0        4   
4                family       0       1  30.0        1       0        1   
...                 ...     ...     ...   ...      ...     ...      ...   
10555    romance family       0       1  58.0        1       0        1   
10556            career       1       0  24.0        1       1        1   
10557     entertainment       1       0  34.0        1       1        0   
10558      conversation       1       1  28.0        1       0        3   
10559            career       1       1  56.0        1       0        1   

       parenthood  reflection  duration  
0               1           0         4  
1               1           0         4  
2               1           0         3  
3               1           0         2  
4               1           0         1  
...           ...         ...       ...  
10555           0           0         0  
10556           1           0         3  
10557           1           0         3  
10558           1           0         3  
10559           0           0         2  

[10483 rows x 12 columns]

In [63]:
train_unlabeled

hmid                                             moment   age  \
0       27673  went successful date someone felt sympathy con...  35.0   
1       27675                              went gym morning yoga  30.0   
2       27678                               meditated last night  23.0   
3       27679     made new recipe peasant bread came spectacular  30.0   
4       27680           got gift elder brother really surprising  23.0   
...       ...                                                ...   ...   
72319  128761                                spent time daughter  40.0   
72320  128762     husband announced getting decent bonus quarter  48.0   
72321  128763                                        pepsi drink  29.0   
72322  128764                     cuddling girlfriend last night  23.0   
72323  128766                           great workout last night  35.0   

       country  gender  married  parenthood  reflection  duration  
0            1       1        3           0           0         3  
1            1       0        1           1           0         3  
2            0       1        3           0           0         3  
3            1       1        3           0           0         4  
4            0       1        3           0           0         3  
...        ...     ...      ...         ...         ...       ...  
72319        1       0        3           1           0         4  
72320        1       0        1           1           0         3  
72321        1       1        3           0           0         0  
72322        1       1        3           0           0         2  
72323        1       1        3           0           0         3  

[71771 rows x 9 columns]

In [64]:
print(train_labeled['country'].unique())
print(train_labeled['country'].describe())

[0 1]
count    10483.000000
mean         0.799580
std          0.400334
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: country, dtype: float64


In [65]:
train_labeled.corr()['social']

hmid         -0.021528
agency       -0.257795
social        1.000000
age           0.054685
country      -0.033266
gender       -0.084028
married      -0.122568
parenthood    0.164944
reflection    0.041243
duration      0.044728
Name: social, dtype: float64

In [66]:
train_labeled.corr()['agency']

hmid         -0.002089
agency        1.000000
social       -0.257795
age          -0.083176
country      -0.006700
gender        0.073615
married       0.097052
parenthood   -0.124688
reflection   -0.023294
duration      0.069562
Name: agency, dtype: float64

In [67]:
# run this in conda terminal
# conda install -c conda-forge spacy
# python -m spacy download en_core_web_sm

In [68]:
!python -m spacy download en_core_web_md 

[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


2022-03-25 03:04:57.216587: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-25 03:04:57.216772: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [69]:
def vectors(nlp, data):
    vectors = []
    for row in data[:, 0]:
        doc = nlp(row)
        vectors.append(doc.vector)
    return np.array(vectors)

In [70]:
train_cols = [1, 2, 5, 6, 7, 8, 9, 10, 11]
X_labeled_train = train_labeled.iloc[:, train_cols].values
y_agency_labeled_train = train_labeled.iloc[:, 3].values
y_social_labeled_train = train_labeled.iloc[:, 4].values

In [71]:
import spacy
nlp = spacy.load('en_core_web_md')
train_vectors = vectors(nlp, X_labeled_train)

In [72]:
test_cols = [1, 2, 3, 4, 5, 6, 7, 8, 9]
X_labeled_test = test_labeled.iloc[:, test_cols].values
y_agency_labeled_test = test_labeled.iloc[:, 10].values
y_social_labeled_test = test_labeled.iloc[:, 11].values
test_vectors = vectors(nlp, X_labeled_test)

## Random Forest Classifier

In [73]:
from sklearn.ensemble import RandomForestClassifier
rf_model_agency = RandomForestClassifier(n_estimators = 200)
rf_model_agency.fit(train_vectors, y_agency_labeled_train)
y_pred_rf_agency = rf_model_agency.predict(test_vectors)

In [74]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
def evaluate(y_true, y_pred):
    # print evaluation results for model
    # print confusion matrix
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    # accuracy
    print("Accuracy: ", accuracy_score(y_true, y_pred))
    # precision
    print("Precision: ", precision_score(y_true, y_pred))
    # recall
    print("Recall ", recall_score(y_true, y_pred))
    # f-measure
    print("F1: ", f1_score(y_true, y_pred))

In [75]:
evaluate(y_agency_labeled_test, y_pred_rf_agency)

Confusion Matrix:
[[  590  4309]
 [  206 11560]]
Accuracy:  0.729072907290729
Precision:  0.7284643014682715
Recall  0.9824919258881523
F1:  0.8366202279717748


In [76]:
rf_model_social = RandomForestClassifier(n_estimators = 200)
rf_model_social.fit(train_vectors, y_social_labeled_train)
y_pred_rf_social = rf_model_social.predict(test_vectors)

In [77]:
evaluate(y_social_labeled_test, y_pred_rf_social)

Confusion Matrix:
[[4829 2322]
 [ 675 8839]]
Accuracy:  0.8201620162016202
Precision:  0.7919541259743751
Recall  0.9290519234811856
F1:  0.8550423216444983


## SVM Classifier

In [78]:
from sklearn import svm
svm_model_agency = svm.SVC()
svm_model_agency.fit(train_vectors, y_agency_labeled_train)
y_pred_svm_agency = svm_model_agency.predict(test_vectors)

In [79]:
evaluate(y_agency_labeled_test, y_pred_svm_agency)

Confusion Matrix:
[[ 1324  3575]
 [  561 11205]]
Accuracy:  0.7518151815181519
Precision:  0.7581190798376184
Recall  0.952320244773075
F1:  0.8441949822948843


In [80]:
svm_model_social = svm.SVC()
svm_model_social.fit(train_vectors, y_social_labeled_train)
y_pred_svm_social = svm_model_social.predict(test_vectors)

In [81]:
evaluate(y_social_labeled_test, y_pred_svm_social)

Confusion Matrix:
[[6190  961]
 [1159 8355]]
Accuracy:  0.8727872787278728
Precision:  0.8968441391155002
Recall  0.878179524910658
F1:  0.8874137015400957


## XGBoost Classifier

In [82]:
from xgboost import XGBClassifier
xg_model_agency = XGBClassifier()
xg_model_agency.fit(train_vectors, y_agency_labeled_train)
y_pred_xg_agency = xg_model_agency.predict(test_vectors)

C:\Users\parit\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
C:\Users\parit\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[03:08:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [83]:
evaluate(y_agency_labeled_test, y_pred_xg_agency)

Confusion Matrix:
[[ 2239  2660]
 [ 1588 10178]]
Accuracy:  0.7450945094509451
Precision:  0.7928026172300982
Recall  0.8650348461669216
F1:  0.827345147130548


In [84]:
xg_model_social = XGBClassifier()
xg_model_social.fit(train_vectors, y_social_labeled_train)
y_pred_xg_social = xg_model_social.predict(test_vectors)

[03:08:48] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\parit\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [85]:
evaluate(y_social_labeled_test, y_pred_xg_social)

Confusion Matrix:
[[4259 2892]
 [ 562 8952]]
Accuracy:  0.7927392739273927
Precision:  0.7558257345491388
Recall  0.9409291570317427
F1:  0.8382807378968068


## CatBoost Classifier

In [86]:
from catboost import CatBoostClassifier
cb_model_agency = CatBoostClassifier()
cb_model_agency.fit(train_vectors, y_agency_labeled_train)
y_pred_cb_agency = cb_model_agency.predict(test_vectors)

Learning rate set to 0.028098
0:	learn: 0.6844458	total: 177ms	remaining: 2m 57s
1:	learn: 0.6756154	total: 199ms	remaining: 1m 39s
2:	learn: 0.6670529	total: 221ms	remaining: 1m 13s
3:	learn: 0.6594306	total: 242ms	remaining: 1m
4:	learn: 0.6513131	total: 262ms	remaining: 52.2s
5:	learn: 0.6439651	total: 312ms	remaining: 51.7s
6:	learn: 0.6369594	total: 332ms	remaining: 47.1s
7:	learn: 0.6298898	total: 352ms	remaining: 43.7s
8:	learn: 0.6234484	total: 372ms	remaining: 41s
9:	learn: 0.6170745	total: 393ms	remaining: 38.9s
10:	learn: 0.6122808	total: 419ms	remaining: 37.6s
11:	learn: 0.6069741	total: 439ms	remaining: 36.2s
12:	learn: 0.6017464	total: 460ms	remaining: 34.9s
13:	learn: 0.5961827	total: 484ms	remaining: 34.1s
14:	learn: 0.5923722	total: 505ms	remaining: 33.1s
15:	learn: 0.5876744	total: 524ms	remaining: 32.3s
16:	learn: 0.5833652	total: 544ms	remaining: 31.5s
17:	learn: 0.5793022	total: 564ms	remaining: 30.8s
18:	learn: 0.5758030	total: 584ms	remaining: 30.2s
19:	learn: 0.

165:	learn: 0.4331049	total: 4.05s	remaining: 20.4s
166:	learn: 0.4326848	total: 4.08s	remaining: 20.3s
167:	learn: 0.4322844	total: 4.1s	remaining: 20.3s
168:	learn: 0.4319566	total: 4.12s	remaining: 20.3s
169:	learn: 0.4316352	total: 4.15s	remaining: 20.3s
170:	learn: 0.4311610	total: 4.17s	remaining: 20.2s
171:	learn: 0.4307213	total: 4.19s	remaining: 20.2s
172:	learn: 0.4303182	total: 4.22s	remaining: 20.2s
173:	learn: 0.4299437	total: 4.24s	remaining: 20.1s
174:	learn: 0.4294583	total: 4.27s	remaining: 20.1s
175:	learn: 0.4290845	total: 4.29s	remaining: 20.1s
176:	learn: 0.4286909	total: 4.32s	remaining: 20.1s
177:	learn: 0.4283582	total: 4.34s	remaining: 20s
178:	learn: 0.4279451	total: 4.36s	remaining: 20s
179:	learn: 0.4275597	total: 4.39s	remaining: 20s
180:	learn: 0.4271289	total: 4.41s	remaining: 20s
181:	learn: 0.4267648	total: 4.44s	remaining: 19.9s
182:	learn: 0.4263623	total: 4.46s	remaining: 19.9s
183:	learn: 0.4260189	total: 4.49s	remaining: 19.9s
184:	learn: 0.4257205

326:	learn: 0.3805052	total: 8.13s	remaining: 16.7s
327:	learn: 0.3801850	total: 8.16s	remaining: 16.7s
328:	learn: 0.3798358	total: 8.19s	remaining: 16.7s
329:	learn: 0.3795914	total: 8.21s	remaining: 16.7s
330:	learn: 0.3792704	total: 8.24s	remaining: 16.6s
331:	learn: 0.3789292	total: 8.26s	remaining: 16.6s
332:	learn: 0.3786624	total: 8.29s	remaining: 16.6s
333:	learn: 0.3783415	total: 8.31s	remaining: 16.6s
334:	learn: 0.3780880	total: 8.34s	remaining: 16.5s
335:	learn: 0.3778491	total: 8.36s	remaining: 16.5s
336:	learn: 0.3775008	total: 8.38s	remaining: 16.5s
337:	learn: 0.3772001	total: 8.41s	remaining: 16.5s
338:	learn: 0.3769318	total: 8.43s	remaining: 16.4s
339:	learn: 0.3766235	total: 8.45s	remaining: 16.4s
340:	learn: 0.3763051	total: 8.48s	remaining: 16.4s
341:	learn: 0.3760574	total: 8.5s	remaining: 16.4s
342:	learn: 0.3757885	total: 8.52s	remaining: 16.3s
343:	learn: 0.3755310	total: 8.55s	remaining: 16.3s
344:	learn: 0.3752318	total: 8.57s	remaining: 16.3s
345:	learn: 0

490:	learn: 0.3272292	total: 11.9s	remaining: 12.4s
491:	learn: 0.3268556	total: 12s	remaining: 12.3s
492:	learn: 0.3265178	total: 12s	remaining: 12.3s
493:	learn: 0.3262736	total: 12s	remaining: 12.3s
494:	learn: 0.3260047	total: 12s	remaining: 12.3s
495:	learn: 0.3256574	total: 12s	remaining: 12.2s
496:	learn: 0.3253682	total: 12.1s	remaining: 12.2s
497:	learn: 0.3251589	total: 12.1s	remaining: 12.2s
498:	learn: 0.3248232	total: 12.1s	remaining: 12.1s
499:	learn: 0.3244789	total: 12.1s	remaining: 12.1s
500:	learn: 0.3241215	total: 12.1s	remaining: 12.1s
501:	learn: 0.3238572	total: 12.2s	remaining: 12.1s
502:	learn: 0.3236463	total: 12.2s	remaining: 12s
503:	learn: 0.3233394	total: 12.2s	remaining: 12s
504:	learn: 0.3230638	total: 12.2s	remaining: 12s
505:	learn: 0.3228240	total: 12.2s	remaining: 12s
506:	learn: 0.3225156	total: 12.3s	remaining: 11.9s
507:	learn: 0.3221496	total: 12.3s	remaining: 11.9s
508:	learn: 0.3218636	total: 12.3s	remaining: 11.9s
509:	learn: 0.3216057	total: 1

649:	learn: 0.2836277	total: 15.2s	remaining: 8.21s
650:	learn: 0.2833306	total: 15.3s	remaining: 8.18s
651:	learn: 0.2830662	total: 15.3s	remaining: 8.16s
652:	learn: 0.2827754	total: 15.3s	remaining: 8.13s
653:	learn: 0.2825994	total: 15.3s	remaining: 8.11s
654:	learn: 0.2823164	total: 15.3s	remaining: 8.08s
655:	learn: 0.2820348	total: 15.4s	remaining: 8.06s
656:	learn: 0.2817743	total: 15.4s	remaining: 8.03s
657:	learn: 0.2815430	total: 15.4s	remaining: 8.01s
658:	learn: 0.2813135	total: 15.4s	remaining: 7.99s
659:	learn: 0.2810673	total: 15.5s	remaining: 7.96s
660:	learn: 0.2808229	total: 15.5s	remaining: 7.94s
661:	learn: 0.2805561	total: 15.5s	remaining: 7.92s
662:	learn: 0.2802854	total: 15.5s	remaining: 7.89s
663:	learn: 0.2800391	total: 15.6s	remaining: 7.87s
664:	learn: 0.2797672	total: 15.6s	remaining: 7.84s
665:	learn: 0.2795485	total: 15.6s	remaining: 7.82s
666:	learn: 0.2792807	total: 15.6s	remaining: 7.79s
667:	learn: 0.2790675	total: 15.6s	remaining: 7.77s
668:	learn: 

809:	learn: 0.2471281	total: 18.6s	remaining: 4.36s
810:	learn: 0.2469043	total: 18.6s	remaining: 4.33s
811:	learn: 0.2466499	total: 18.6s	remaining: 4.31s
812:	learn: 0.2464286	total: 18.6s	remaining: 4.29s
813:	learn: 0.2462529	total: 18.7s	remaining: 4.26s
814:	learn: 0.2460333	total: 18.7s	remaining: 4.24s
815:	learn: 0.2457867	total: 18.7s	remaining: 4.22s
816:	learn: 0.2455640	total: 18.7s	remaining: 4.19s
817:	learn: 0.2453083	total: 18.7s	remaining: 4.17s
818:	learn: 0.2450688	total: 18.8s	remaining: 4.14s
819:	learn: 0.2448571	total: 18.8s	remaining: 4.12s
820:	learn: 0.2446638	total: 18.8s	remaining: 4.1s
821:	learn: 0.2444031	total: 18.8s	remaining: 4.08s
822:	learn: 0.2441508	total: 18.8s	remaining: 4.05s
823:	learn: 0.2440270	total: 18.9s	remaining: 4.03s
824:	learn: 0.2439071	total: 18.9s	remaining: 4s
825:	learn: 0.2436719	total: 18.9s	remaining: 3.98s
826:	learn: 0.2434943	total: 18.9s	remaining: 3.96s
827:	learn: 0.2433046	total: 18.9s	remaining: 3.94s
828:	learn: 0.24

975:	learn: 0.2148433	total: 22.1s	remaining: 542ms
976:	learn: 0.2146661	total: 22.1s	remaining: 520ms
977:	learn: 0.2145291	total: 22.1s	remaining: 497ms
978:	learn: 0.2143566	total: 22.1s	remaining: 475ms
979:	learn: 0.2141695	total: 22.1s	remaining: 452ms
980:	learn: 0.2139749	total: 22.2s	remaining: 429ms
981:	learn: 0.2137989	total: 22.2s	remaining: 407ms
982:	learn: 0.2135971	total: 22.2s	remaining: 384ms
983:	learn: 0.2134233	total: 22.2s	remaining: 361ms
984:	learn: 0.2132327	total: 22.2s	remaining: 339ms
985:	learn: 0.2130343	total: 22.3s	remaining: 316ms
986:	learn: 0.2128935	total: 22.3s	remaining: 294ms
987:	learn: 0.2127495	total: 22.3s	remaining: 271ms
988:	learn: 0.2126035	total: 22.3s	remaining: 248ms
989:	learn: 0.2123793	total: 22.4s	remaining: 226ms
990:	learn: 0.2122289	total: 22.4s	remaining: 203ms
991:	learn: 0.2120561	total: 22.4s	remaining: 181ms
992:	learn: 0.2119515	total: 22.4s	remaining: 158ms
993:	learn: 0.2117351	total: 22.4s	remaining: 135ms
994:	learn: 

In [87]:
evaluate(y_agency_labeled_test, y_pred_cb_agency)

Confusion Matrix:
[[ 2098  2801]
 [ 1175 10591]]
Accuracy:  0.7614161416141614
Precision:  0.7908452807646356
Recall  0.9001359850416454
F1:  0.8419588202559822


In [88]:
cb_model_social = CatBoostClassifier()
cb_model_social.fit(train_vectors, y_social_labeled_train)
y_pred_cb_social = cb_model_social.predict(test_vectors)

Learning rate set to 0.028098
0:	learn: 0.6809370	total: 21.9ms	remaining: 21.9s
1:	learn: 0.6691491	total: 42.4ms	remaining: 21.2s
2:	learn: 0.6581171	total: 64.1ms	remaining: 21.3s
3:	learn: 0.6477904	total: 85.3ms	remaining: 21.3s
4:	learn: 0.6379094	total: 106ms	remaining: 21.1s
5:	learn: 0.6290149	total: 129ms	remaining: 21.3s
6:	learn: 0.6197538	total: 150ms	remaining: 21.3s
7:	learn: 0.6108653	total: 171ms	remaining: 21.2s
8:	learn: 0.6024124	total: 193ms	remaining: 21.2s
9:	learn: 0.5944800	total: 214ms	remaining: 21.2s
10:	learn: 0.5869220	total: 241ms	remaining: 21.7s
11:	learn: 0.5796954	total: 269ms	remaining: 22.2s
12:	learn: 0.5716302	total: 290ms	remaining: 22s
13:	learn: 0.5643178	total: 311ms	remaining: 21.9s
14:	learn: 0.5571106	total: 330ms	remaining: 21.7s
15:	learn: 0.5494138	total: 351ms	remaining: 21.6s
16:	learn: 0.5440624	total: 371ms	remaining: 21.5s
17:	learn: 0.5381954	total: 392ms	remaining: 21.4s
18:	learn: 0.5318027	total: 412ms	remaining: 21.3s
19:	learn

164:	learn: 0.2997573	total: 3.56s	remaining: 18s
165:	learn: 0.2991372	total: 3.58s	remaining: 18s
166:	learn: 0.2986199	total: 3.6s	remaining: 18s
167:	learn: 0.2980811	total: 3.62s	remaining: 17.9s
168:	learn: 0.2974922	total: 3.64s	remaining: 17.9s
169:	learn: 0.2970911	total: 3.66s	remaining: 17.9s
170:	learn: 0.2965798	total: 3.68s	remaining: 17.9s
171:	learn: 0.2959553	total: 3.7s	remaining: 17.8s
172:	learn: 0.2953829	total: 3.72s	remaining: 17.8s
173:	learn: 0.2949662	total: 3.74s	remaining: 17.8s
174:	learn: 0.2944127	total: 3.76s	remaining: 17.7s
175:	learn: 0.2939060	total: 3.78s	remaining: 17.7s
176:	learn: 0.2933536	total: 3.81s	remaining: 17.7s
177:	learn: 0.2927475	total: 3.83s	remaining: 17.7s
178:	learn: 0.2922085	total: 3.85s	remaining: 17.7s
179:	learn: 0.2917025	total: 3.87s	remaining: 17.6s
180:	learn: 0.2912161	total: 3.89s	remaining: 17.6s
181:	learn: 0.2908650	total: 3.91s	remaining: 17.6s
182:	learn: 0.2904044	total: 3.93s	remaining: 17.6s
183:	learn: 0.289877

323:	learn: 0.2396963	total: 6.97s	remaining: 14.5s
324:	learn: 0.2394116	total: 6.99s	remaining: 14.5s
325:	learn: 0.2390730	total: 7.01s	remaining: 14.5s
326:	learn: 0.2387769	total: 7.03s	remaining: 14.5s
327:	learn: 0.2384736	total: 7.05s	remaining: 14.5s
328:	learn: 0.2381950	total: 7.07s	remaining: 14.4s
329:	learn: 0.2378506	total: 7.11s	remaining: 14.4s
330:	learn: 0.2374676	total: 7.13s	remaining: 14.4s
331:	learn: 0.2372092	total: 7.15s	remaining: 14.4s
332:	learn: 0.2368965	total: 7.17s	remaining: 14.4s
333:	learn: 0.2366409	total: 7.19s	remaining: 14.3s
334:	learn: 0.2363275	total: 7.21s	remaining: 14.3s
335:	learn: 0.2360304	total: 7.23s	remaining: 14.3s
336:	learn: 0.2356570	total: 7.25s	remaining: 14.3s
337:	learn: 0.2353335	total: 7.27s	remaining: 14.2s
338:	learn: 0.2350361	total: 7.29s	remaining: 14.2s
339:	learn: 0.2347073	total: 7.32s	remaining: 14.2s
340:	learn: 0.2343506	total: 7.34s	remaining: 14.2s
341:	learn: 0.2340225	total: 7.36s	remaining: 14.2s
342:	learn: 

485:	learn: 0.1907799	total: 10.6s	remaining: 11.2s
486:	learn: 0.1905378	total: 10.6s	remaining: 11.1s
487:	learn: 0.1903135	total: 10.6s	remaining: 11.1s
488:	learn: 0.1900666	total: 10.6s	remaining: 11.1s
489:	learn: 0.1897973	total: 10.6s	remaining: 11.1s
490:	learn: 0.1895420	total: 10.7s	remaining: 11.1s
491:	learn: 0.1893415	total: 10.7s	remaining: 11s
492:	learn: 0.1890843	total: 10.7s	remaining: 11s
493:	learn: 0.1888087	total: 10.7s	remaining: 11s
494:	learn: 0.1885470	total: 10.8s	remaining: 11s
495:	learn: 0.1882956	total: 10.8s	remaining: 11s
496:	learn: 0.1880368	total: 10.8s	remaining: 10.9s
497:	learn: 0.1877206	total: 10.8s	remaining: 10.9s
498:	learn: 0.1875526	total: 10.9s	remaining: 10.9s
499:	learn: 0.1872870	total: 10.9s	remaining: 10.9s
500:	learn: 0.1869976	total: 10.9s	remaining: 10.9s
501:	learn: 0.1867891	total: 10.9s	remaining: 10.8s
502:	learn: 0.1865569	total: 10.9s	remaining: 10.8s
503:	learn: 0.1863268	total: 11s	remaining: 10.8s
504:	learn: 0.1860487	to

646:	learn: 0.1547679	total: 14.3s	remaining: 7.78s
647:	learn: 0.1545569	total: 14.3s	remaining: 7.76s
648:	learn: 0.1543764	total: 14.3s	remaining: 7.74s
649:	learn: 0.1541659	total: 14.3s	remaining: 7.72s
650:	learn: 0.1540149	total: 14.4s	remaining: 7.69s
651:	learn: 0.1538108	total: 14.4s	remaining: 7.67s
652:	learn: 0.1537425	total: 14.4s	remaining: 7.65s
653:	learn: 0.1535399	total: 14.4s	remaining: 7.63s
654:	learn: 0.1533915	total: 14.4s	remaining: 7.6s
655:	learn: 0.1531853	total: 14.5s	remaining: 7.58s
656:	learn: 0.1530212	total: 14.5s	remaining: 7.56s
657:	learn: 0.1528321	total: 14.5s	remaining: 7.54s
658:	learn: 0.1526741	total: 14.5s	remaining: 7.52s
659:	learn: 0.1525365	total: 14.5s	remaining: 7.5s
660:	learn: 0.1523260	total: 14.6s	remaining: 7.47s
661:	learn: 0.1521333	total: 14.6s	remaining: 7.45s
662:	learn: 0.1519170	total: 14.6s	remaining: 7.43s
663:	learn: 0.1517439	total: 14.6s	remaining: 7.41s
664:	learn: 0.1515890	total: 14.7s	remaining: 7.39s
665:	learn: 0.

807:	learn: 0.1270491	total: 17.9s	remaining: 4.25s
808:	learn: 0.1269156	total: 17.9s	remaining: 4.23s
809:	learn: 0.1267519	total: 17.9s	remaining: 4.21s
810:	learn: 0.1265727	total: 17.9s	remaining: 4.18s
811:	learn: 0.1263790	total: 18s	remaining: 4.16s
812:	learn: 0.1261798	total: 18s	remaining: 4.14s
813:	learn: 0.1260730	total: 18s	remaining: 4.12s
814:	learn: 0.1258996	total: 18s	remaining: 4.09s
815:	learn: 0.1257425	total: 18.1s	remaining: 4.07s
816:	learn: 0.1256506	total: 18.1s	remaining: 4.05s
817:	learn: 0.1255151	total: 18.1s	remaining: 4.03s
818:	learn: 0.1253394	total: 18.1s	remaining: 4s
819:	learn: 0.1252624	total: 18.1s	remaining: 3.98s
820:	learn: 0.1251193	total: 18.2s	remaining: 3.96s
821:	learn: 0.1249896	total: 18.2s	remaining: 3.94s
822:	learn: 0.1248590	total: 18.2s	remaining: 3.91s
823:	learn: 0.1246938	total: 18.2s	remaining: 3.89s
824:	learn: 0.1245739	total: 18.2s	remaining: 3.87s
825:	learn: 0.1243987	total: 18.3s	remaining: 3.85s
826:	learn: 0.1242391	t

969:	learn: 0.1049599	total: 21.4s	remaining: 663ms
970:	learn: 0.1048692	total: 21.5s	remaining: 641ms
971:	learn: 0.1047358	total: 21.5s	remaining: 619ms
972:	learn: 0.1045975	total: 21.5s	remaining: 597ms
973:	learn: 0.1045157	total: 21.5s	remaining: 575ms
974:	learn: 0.1044113	total: 21.6s	remaining: 553ms
975:	learn: 0.1042891	total: 21.6s	remaining: 531ms
976:	learn: 0.1041520	total: 21.6s	remaining: 509ms
977:	learn: 0.1040194	total: 21.6s	remaining: 486ms
978:	learn: 0.1039331	total: 21.6s	remaining: 464ms
979:	learn: 0.1037916	total: 21.7s	remaining: 442ms
980:	learn: 0.1036434	total: 21.7s	remaining: 420ms
981:	learn: 0.1035062	total: 21.7s	remaining: 398ms
982:	learn: 0.1034090	total: 21.7s	remaining: 376ms
983:	learn: 0.1033169	total: 21.8s	remaining: 354ms
984:	learn: 0.1031837	total: 21.8s	remaining: 332ms
985:	learn: 0.1030809	total: 21.8s	remaining: 310ms
986:	learn: 0.1029538	total: 21.8s	remaining: 287ms
987:	learn: 0.1027967	total: 21.8s	remaining: 265ms
988:	learn: 

In [89]:
evaluate(y_social_labeled_test, y_pred_cb_social)

Confusion Matrix:
[[4479 2672]
 [ 560 8954]]
Accuracy:  0.806060606060606
Precision:  0.7701703079305006
Recall  0.9411393735547614
F1:  0.8471144749290445


# BERT

In [90]:
#Install simpletransformers
#conda install pytorch cpuonly -c pytorch
#pip install simpletransformers

In [95]:
from simpletransformers.classification import ClassificationModel

In [96]:
df = pd.DataFrame({'text': X_labeled_train[:, 0],'label':y_agency_labeled_train})
arr = []
for i in range(0, len(X_labeled_test)):
    arr.append(X_labeled_test[i, 0])
model = ClassificationModel('bert', 'bert-base-cased', use_cuda=False, args = {"num_train_epochs": 2,"use_multiprocessing":True,"overwrite_output_dir":True})
model.train_model(df)
y_pred_bert_agency = model.predict(arr)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at b

  0%|          | 0/10483 [00:00<?, ?it/s]

Epoch:   0%|          | 0/2 [00:00<?, ?it/s]

Running Epoch 0 of 2:   0%|          | 0/1311 [00:00<?, ?it/s]

Running Epoch 1 of 2:   0%|          | 0/1311 [00:00<?, ?it/s]

  0%|          | 0/16665 [00:00<?, ?it/s]

  0%|          | 0/2084 [00:00<?, ?it/s]

In [97]:
evaluate(y_agency_labeled_test, y_pred_bert_agency[0])

Confusion Matrix:
[[3899 1000]
 [2063 9703]]
Accuracy:  0.8162016201620163
Precision:  0.9065682518919929
Recall  0.8246642869284379
F1:  0.8636788464106101


In [98]:
df = pd.DataFrame({'text': X_labeled_train[:, 0],'label':y_social_labeled_train})
arr = []
for i in range(0, len(X_labeled_test)):
    arr.append(X_labeled_test[i, 0])
model = ClassificationModel('bert', 'bert-base-cased', use_cuda=False, args = {"num_train_epochs": 2,"use_multiprocessing":True,"overwrite_output_dir":True})
model.train_model(df)
y_pred_bert_social = model.predict(arr)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at b

  0%|          | 0/10483 [00:00<?, ?it/s]

C:\Users\parit\anaconda3\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch:   0%|          | 0/2 [00:00<?, ?it/s]

Running Epoch 0 of 2:   0%|          | 0/1311 [00:00<?, ?it/s]

Running Epoch 1 of 2:   0%|          | 0/1311 [00:00<?, ?it/s]

  0%|          | 0/16665 [00:00<?, ?it/s]

  0%|          | 0/2084 [00:00<?, ?it/s]

In [99]:
evaluate(y_social_labeled_test, y_pred_bert_social[0])

Confusion Matrix:
[[6784  367]
 [1090 8424]]
Accuracy:  0.9125712571257125
Precision:  0.9582527585030145
Recall  0.8854319949548034
F1:  0.9204042611308385


## Using Unlabeled Training Dataset

In [100]:
train_unlabeled

hmid                                             moment   age  \
0       27673  went successful date someone felt sympathy con...  35.0   
1       27675                              went gym morning yoga  30.0   
2       27678                               meditated last night  23.0   
3       27679     made new recipe peasant bread came spectacular  30.0   
4       27680           got gift elder brother really surprising  23.0   
...       ...                                                ...   ...   
72319  128761                                spent time daughter  40.0   
72320  128762     husband announced getting decent bonus quarter  48.0   
72321  128763                                        pepsi drink  29.0   
72322  128764                     cuddling girlfriend last night  23.0   
72323  128766                           great workout last night  35.0   

       country  gender  married  parenthood  reflection  duration  
0            1       1        3           0           0         3  
1            1       0        1           1           0         3  
2            0       1        3           0           0         3  
3            1       1        3           0           0         4  
4            0       1        3           0           0         3  
...        ...     ...      ...         ...         ...       ...  
72319        1       0        3           1           0         4  
72320        1       0        1           1           0         3  
72321        1       1        3           0           0         0  
72322        1       1        3           0           0         2  
72323        1       1        3           0           0         3  

[71771 rows x 9 columns]

In [101]:
test_unlabeled

hmid                                             moment  reflection  \
0          0  I was able to spend the day with my fiance sho...           0   
1          1                    I was able to play with my cat.           0   
2          2   I was able to clean my room and gold my laundry.           0   
3          3  I spend the day at a party on the beach and I ...           0   
4          4  My cat greeting me when I got home from work -...           0   
...      ...                                                ...         ...   
17210  21892  My wife and I went for a hike last week and we...           1   
17211  21893          I finally hit platinum rank in Overwatch.           1   
17212  21897  One of my long-time friends and I finally ackn...           1   
17213  21898             I earned a professional certification.           1   
17214  21899                            I built a new computer.           1   

      age  country  gender  duration  married  parenthood  
0      28        1       1         1        3           0  
1      28        1       1         2        3           0  
2      28        1       1         2        3           0  
3      24        1       1         3        3           0  
4      24        1       1         3        3           0  
...    ..      ...     ...       ...      ...         ...  
17210  34        1       1         3        1           0  
17211  34        1       1         2        1           0  
17212  34        1       1         1        3           0  
17213  34        1       1         3        3           0  
17214  34        1       1         3        3           0  

[16665 rows x 9 columns]

In [102]:
train_cols = [1, 5, 7, 8, 9, 10, 11]
X_labeled_train = train_labeled.iloc[:, train_cols].values
y_agency_labeled_train = train_labeled.iloc[:, 3].values
y_social_labeled_train = train_labeled.iloc[:, 4].values
train_vectors = vectors(nlp, X_labeled_train)

In [103]:
test_cols = [1, 2, 3, 5, 6, 7, 8]
X_labeled_test = test_labeled.iloc[:, test_cols].values
y_agency_labeled_test = test_labeled.iloc[:, 10].values
y_social_labeled_test = test_labeled.iloc[:, 11].values
test_vectors = vectors(nlp, X_labeled_test)

In [104]:
from sklearn.ensemble import RandomForestClassifier
rf_model_agency = RandomForestClassifier(n_estimators = 200)
rf_model_agency.fit(train_vectors, y_agency_labeled_train)
y_pred_rf_agency = rf_model_agency.predict(test_vectors)

In [105]:
evaluate(y_agency_labeled_test, y_pred_rf_agency)

Confusion Matrix:
[[  624  4275]
 [  234 11532]]
Accuracy:  0.7294329432943294
Precision:  0.7295501992788005
Recall  0.9801121876593575
F1:  0.8364704602328364


In [106]:
train_cols = [1, 2, 4, 5, 6, 7, 8]
X_unlabeled_train = train_unlabeled.iloc[:, train_cols].values
train_vectors = vectors(nlp, X_unlabeled_train)

In [107]:
y_unlabeled_rf_agency = rf_model_agency.predict(train_vectors)

In [108]:
train_cols_labeled = [1, 5, 7, 8, 9, 10, 11]

train_cols_unlabeled = [1, 2, 4, 5, 6, 7, 8]

In [109]:
combined_df_train_X = pd.concat([train_labeled.iloc[:, train_cols_labeled], train_unlabeled.iloc[:, train_cols_unlabeled]], axis=0)

In [110]:
train_vectors = vectors(nlp, combined_df_train_X.values)

In [111]:
combined_df_train_y = pd.concat([train_labeled.iloc[:, 10], pd.Series(y_unlabeled_rf_agency)], axis=0)

In [112]:
rf_model_agency.fit(train_vectors, combined_df_train_y)
y_pred_rf_agency = rf_model_agency.predict(test_vectors)

In [113]:
evaluate(y_agency_labeled_test, y_pred_rf_agency)

Confusion Matrix:
[[   98  4801]
 [   22 11744]]
Accuracy:  0.7105910591059106
Precision:  0.7098216983983077
Recall  0.9981302056773755
F1:  0.8296421885486207


In [114]:
#Social
train_cols = [1, 5, 7, 8, 9, 10, 11]
X_labeled_train = train_labeled.iloc[:, train_cols].values
y_agency_labeled_train = train_labeled.iloc[:, 3].values
y_social_labeled_train = train_labeled.iloc[:, 4].values
train_vectors = vectors(nlp, X_labeled_train)
rf_model_social = RandomForestClassifier(n_estimators = 200)
rf_model_social.fit(train_vectors, y_social_labeled_train)
y_pred_rf_social = rf_model_social.predict(test_vectors)

In [115]:
evaluate(y_social_labeled_test, y_pred_rf_social)

Confusion Matrix:
[[5025 2126]
 [ 730 8784]]
Accuracy:  0.8286228622862286
Precision:  0.8051329055912008
Recall  0.9232709690981711
F1:  0.8601645123384254


In [116]:
train_cols = [1, 2, 4, 5, 6, 7, 8]
X_unlabeled_train = train_unlabeled.iloc[:, train_cols].values
train_vectors = vectors(nlp, X_unlabeled_train)
y_unlabeled_rf_social = rf_model_social.predict(train_vectors)

In [117]:
train_cols_labeled = [1, 5, 7, 8, 9, 10, 11]
train_cols_unlabeled = [1, 2, 4, 5, 6, 7, 8]

In [118]:
combined_df_train_X = pd.concat([train_labeled.iloc[:, train_cols_labeled], train_unlabeled.iloc[:, train_cols_unlabeled]], axis=0)

In [119]:
train_vectors = vectors(nlp, combined_df_train_X.values)

In [120]:
combined_df_train_y = pd.concat([train_labeled.iloc[:, 10], pd.Series(y_unlabeled_rf_social)], axis=0)

In [121]:
rf_model_social.fit(train_vectors, combined_df_train_y)
y_pred_rf_social = rf_model_social.predict(test_vectors)

In [122]:
evaluate(y_social_labeled_test, y_pred_rf_social)

Confusion Matrix:
[[5961 1190]
 [1308 8206]]
Accuracy:  0.8501050105010501
Precision:  0.873350361856109
Recall  0.8625183939457641
F1:  0.8679005817028028
